import { useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';

import 'react-tooltip/dist/react-tooltip.css';

const startColor = {
  r: '190',
  g: '18',
  b: '60',
  a: '1',
};

export default function Home() {
  const [showColor, setShowColor] = useState(false);
  const [color, setColor] = useState(startColor);
  const [brushSize, setBrushSize] = useState(10);

  const onColorChange = (color) => {
    setColor(color.rgb);
  };

  return (
    <>
      <Head>
        <title>PaintPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar
          {...{
            showColor,
            setShowColor,
            color,
            onColorChange,
            brushSize,
            setBrushSize,
          }}
        />
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </>
  );
}
